# Round-3 CONFIRMED findings: control (6)

## [1] P0 - NowView is dead in the composed app: shell passes `client`, view reads `token`
File: C:\Users\vagrant\Downloads\EnergyPod\pod-manager\web\src\views\now\NowView.tsx:367 (broken production path)

DETAIL: The shell renders every injected view as `<CurrentComponent client={viewClient ?? client} />` (web/src/app/AppShell.tsx:190, views.ts:13-17), but NowView is the only view whose signature is `({ token }: { token: string })` (NowView.tsx:367) — every other view takes `client: ApiClient`. main.tsx:19-28 mounts `now: adapt(NowView)` where `adapt(component: unknown)` erases the prop-type mismatch, so tsc passes. In the real app `token` is undefined, `createApiClient(undefined)` (NowView.tsx:368) sends `Authorization: Bearer undefined`: the snapshot load shows a permanent `authentication_required` error whose Retry can never succeed, the events ticket POST 401s and the reconnect loop (NowView.tsx:548-559) retries every 3 s forever. Arm, dispatch, stop, and both acknowledgements are unreachable from the Now view in production. All 126 tests pass because NowView.test.tsx:184 renders `<NowView token="operator-session-token" />` standalone and no suite composes AppShell with the real views (only main.tsx:34 composes them). Even with the prop fixed, building a private client bypasses the SharedDataPlane whose documented purpose (SharedDataPlane.ts:1-11) is that a view never opens a second socket, buys a second ticket, or races the shell's snapshot.

FIX: Change NowView to accept `{ client }: ShellViewProps` and use the shell-injected shared client (as Home/Batteries/Activity do); delete the private createApiClient and its second WS connection. Add one composition test rendering AppShell with the real views map.

VERDICT: Confirmed at every hop, statically and with live runs. (1) AppShell.tsx:190 renders <CurrentComponent client={viewClient ?? client} />, and for the "now" view CurrentComponent is NowView (main.tsx:26); NowView.tsx:367 is the only view of four taking { token: string } (HomeView.tsx:323, BatteriesView.tsx:845, ActivityView.tsx:274 all take { client: ApiClient }), so the destructured token is undefined at runtime. (2) The mismatch survives type-checking because main.tsx:19-21 adapt(component: unknown) casts through unknown; I ran tsc --noEmit — exit 0. (3) createApiClient(undefined) does not thro

## [2] P0 - Refused arm/disarm outcomes rendered as lifecycle changes: unit the API refused is shown armed
File: C:\Users\vagrant\Downloads\EnergyPod\pod-manager\web\src\views\now\NowView.tsx:484 (safety misrepresentation)

DETAIL: The `unit.armed`/`unit.disarmed` handler (NowView.tsx:484-505) builds the changed-unit set from `payload.units[].unit_id` only and flips every listed unit to `armed_idle`/`disarmed`. Wire truth: the facade publishes ALL outcomes in those events, including refused ones — `{unit_id, status: "refused", reason: "not_qualified"|"inhibit_latched"|"qualification_unknown"|"actor_failure"|"unknown_unit"}` (src/energypod/application/service.py:501, 533, 913-941). Concrete scenario: MID qualified, LHS not_qualified; operator arms both. The REST response rows honestly show `LHS: refused — not_qualified`, but the `unit.armed` event then flips LHS to armed_idle in the snapshot state. The Now view's facts, derived unit lists (NowView.tsx:570-575), and the Disarm/Charge/Discharge buttons now present LHS as armed and include it in dispatch unit selection, while the unit is actually disarmed. A subsequent dispatch selecting LHS is refused server-side, but the console has already represented refused arming as delivered — the exact refused-shown-as-armed misrepresentation. The same defect exists in the shell banner path (web/src/app/useConsoleData.ts:155-185, `listedUnitIds` ignores status and announces "now armed").

FIX: In applyEvent, patch lifecycle only for entries whose `status` is "armed"/"disarmed"; for refused entries leave state alone (or refetch the snapshot). Apply the same fix to listedUnitIds in useConsoleData.ts.

VERDICT: CONFIRMED as P0 after tracing every link in the chain against production code; the claim survives skeptical review.

Wire truth (verified server-side): arm() publishes unit.armed with the FULL outcomes list including refused rows (src/energypod/application/service.py:501; rows produced by _arm_one at 913-931 with status "refused" and reasons not_qualified/inhibit_latched/qualification_unknown/actor_failure/unknown_unit); disarm() mirrors it at :533 (_disarm_one at 933-941). _publish (service.py:1008-1009) puts the payload on the EventBus verbatim, and the /events WebSocket (src/energypod/api/r

## [3] P0 - emergency_stop.latched / authorization.revoked / inhibit.acknowledged events never applied — latched fleet shown armed and dispatchable
File: C:\Users\vagrant\Downloads\EnergyPod\pod-manager\web\src\views\now\NowView.tsx:461 (safety misrepresentation / stale presented fresh)

DETAIL: applyEvent handles only `intent.accepted`, `unit.armed`, `unit.disarmed` (NowView.tsx:461-507); the `else` branch marks the stream `live` for everything else (536-539). The bus also publishes `emergency_stop.latched` (service.py:663-673), `authorization.revoked` (the latched-inhibit signal the shell itself listens for, useConsoleData.ts:198-210), `inhibit.acknowledged` (service.py:795-802), and `emergency_stop.acknowledged` (service.py:752-755). NowView has no snapshot refresh after its own mutations and no polling — the only refresh triggers are resync, reconnect, and manual Retry. Scenarios: (a) any operator (or the supervisor) latches a stop — every unit is fenced, revoked, and INHIBITED, but Now keeps rendering the units as armed/active with Charge/Discharge enabled, connection "live", nothing dimmed; if the stop originated elsewhere this console shows no stop card at all. (b) The operator acknowledges an inhibit latch — `inhibitOutcome` says latch cleared, but the unit stays lifecycle "inhibited" in the view and the "Acknowledge <unit>" button stays on screen, inviting a redundant ack. Every downstream action is refused by the API, but the control surface presents a latched fleet as armed and controllable with no stale indication, which is stale-presented-fresh on the safety surface.

FIX: Handle `emergency_stop.latched` and `authorization.revoked` (patch affected unit_ids to "inhibited") and the acknowledgement events (patch back toward disarmed or refetch); simplest robust fix is to refetch the snapshot after every successful mutation and on any unhandled lifecycle-bearing event.

VERDICT: CONFIRMED (scenario a), with every link traced in code. Publishers: emergency_stop.latched with unit_ids (src/energypod/application/service.py:663-673); the stop's revoke step (service.py:586) runs through _AsyncAuthorizationRepository.revoke (wired at composition.py:1487, bus publish at composition.py:532-534) emitting authorization.revoked with held unit_ids. Transport: rest.py _stream_events (815-890) forwards every event type unfiltered with contiguous sequences — no forced resync. Consumer: NowView.tsx:461-507 applies only intent.accepted/unit.armed/unit.disarmed; the stop/revocation fram

## [4] P1 - Allowed and Actual facts are frozen at connect time — after a dispatch, the console never shows what the safety system allowed or what is actually happening
File: C:\Users\vagrant\Downloads\EnergyPod\pod-manager\web\src\views\now\NowView.tsx:596 (contract violation (requested/allowed/actual))

DETAIL: The snapshot is adopted at mount (REST, NowView.tsx:398-426), on the WS snapshot frame, on resync, and on manual Retry — nowhere else; there is no polling and no post-mutation refetch, and the only event fields ever applied are requested_power (intent.accepted) and lifecycle. So `authorized_power`, `measured_watts`, `telemetry_age_s`, and `quality` are frozen at connect time for the whole session while the connection indicator says "live" and the facts render undimmed. Concrete scenario: operator opens Now (Allowed: "None yet", Actual: "0 W (2 s ago)"), dispatches 1,500 W discharge. Requested updates via the event/response, but Allowed stays "None yet" forever — the operator can never see what the safety system allowed, the single fact the contract's four-fact card exists for (UI_CONTRACTS.md "Now": four separate facts; roadmap: "Distinguish requested, allowed, and actual power"). Actual keeps showing the pre-dispatch measurement with an age counter that never advances, which actively simulates freshness (roadmap: "Show the age and confidence of important data near the value, especially when it is stale"; UI_CONTRACTS: stale data shown with age, dimmed). For contrast, the shell polls health every 15 s (useConsoleData.ts:218, 272) while NowView's health read runs exactly once per mount (NowView.tsx:430-443).

FIX: Refetch the snapshot after each successful mutation and poll it (or the WS snapshot envelope) on an interval; derive displayed telemetry age from `captured_at`/`telemetry_age_s` at render time so age grows; dim/mark facts whose data predates the current connection.

VERDICT: CONFIRMED after adversarial tracing; every attempted refutation failed.

(1) Client refresh paths are exactly as claimed and exhaustive: snapshot state is set only in the mount REST effect (NowView.tsx:398-426, deps [client, snapshotNonce]; nonce bumped only by the two Retry buttons at 825/922), the WS snapshot frame (453-459, 528-530), resync (509-516, 550-556). No setInterval exists in NowView; submitDispatch (671-729), submitArm/Disarm (645-669), submitStop (731-748), and inhibit-ack (763-774) never refetch. applyEvent (461-507) applies only intent.accepted -> requested_power/expirySeconds 

## [5] P1 - Snapshot adoption ignores snapshot_sequence — older REST data can overwrite newer WS snapshot plus applied events
File: C:\Users\vagrant\Downloads\EnergyPod\pod-manager\web\src\views\now\NowView.tsx:453 (correctness (data plane))

DETAIL: `adoptSnapshot` (NowView.tsx:453-459) and the REST effect (398-426) both call `setSnapshot(wire)` without ever comparing `snapshot_sequence` to the current state. Three concrete reorderings: (a) mount race — the REST GET /snapshot and the WS connection start together; if the WS snapshot frame (seq 12) is adopted and event 13 applied while the slower REST response (captured at seq 10) resolves afterwards, the older REST snapshot overwrites the newer frame plus the applied event (e.g., a unit armed by event 13 silently reverts to disarmed). (b) Manual Retry while live does the same against newer WS state. (c) The resync path (549-555) calls `refetchSnapshot()` and `connect()` back-to-back; both produce fresh snapshots (the reconnect's WS snapshot frame and the REST refetch) that resolve in arbitrary order, so the older one can win the last write. API_CONTRACTS pins `snapshot_sequence` as the client's recovery ordering; the UI contract calls the WS snapshot frame authoritative-first — neither is honored.

FIX: Adopt a snapshot only when `wire.snapshot_sequence >= snapshot?.snapshot_sequence` in both the REST effect and adoptSnapshot (and skip the redundant refetch in the resync path, since the reconnect's snapshot frame is already fresh).

VERDICT: Confirmed by code reading and an empirical probe (temp test, deleted afterward; NowView suite re-passed, tree restored). NowView.tsx:406 (REST effect) and NowView.tsx:456 (adoptSnapshot) are the only snapshot writers and both are unconditional replacements; snapshot_sequence is shape-narrowed (lines 47/83/93) but never compared, and applyEvent (461-507) does not advance the stored sequence, so a later full replace discards applied events. Wire truth: rest.py:707-714 sends a snapshot frame first on EVERY WS connection including reconnects with an `after` cursor, so REST GET /snapshot and the WS

## [6] P1 - Arm checklist green-lights from a frozen snapshot with a vacuous latch test and one-shot health
File: C:\Users\vagrant\Downloads\EnergyPod\pod-manager\web\src\views\now\NowView.tsx:1015 (safety misrepresentation (arm gate))

DETAIL: The readiness list iterates `armableUnits` — units filtered to `lifecycle === "disarmed"` from the last adopted snapshot (NowView.tsx:571) — and prints `unit.lifecycle === "inhibited" ? "inhibit latched" : "latch clear"` (1022-1024). That predicate is unreachable: any unit whose lifecycle is "inhibited" was filtered out of the list, so the dialog can never say anything but "latch clear". When the underlying data IS current this is merely incomplete; when it is stale (a unit latched via `authorization.revoked`, or lost qualification, after the last snapshot — which, per the unhandled-events finding, the view never learns about) the checklist affirmatively prints "qualified, latch clear" and the ARM button submits that unit anyway. Health's `control_readiness.reasons` ("<unit>:inhibit_latched", "<unit>:not_qualified", service.py:892-911) is the live latch signal, but NowView fetches health exactly once per mount (430-443, deps `[client]`) — never on dialog open, never polled — so a latch that appears mid-session still shows "Control readiness: Ready". The API does refuse (defense holds) and the refusal row renders verbatim, but the checklist's whole purpose ("unit qualified, not latched" before the ARM confirmation) is computed from data that cannot answer the question.

FIX: Refresh snapshot and health when the arm dialog opens (or on an interval) so the checklist reads current state; remove the vacuous `lifecycle === "inhibited"` branch and instead derive the latch line from fresh health reasons (e.g., `<unit>:inhibit_latched`) or a refreshed snapshot.

VERDICT: CONCEDED after full adversarial trace; every factual leg of the claim verified against web/src/views/now/NowView.tsx and the server wire truth.

1) Vacuous latch branch — confirmed. NowView.tsx:571 filters armableUnits to lifecycle === "disarmed"; the arm checklist maps over armableUnits (1015) and then tests unit.lifecycle === "inhibited" (1022-1024). The predicate is structurally unreachable (nothing in the view ever sets lifecycle to "inhibited" — applyEvent's handlers only set "armed_idle"/"disarmed", 484-506), so the dialog can only ever print "latch clear" for listed units. The "inhibit 

