"""Evidence-derived reference contracts for the EnergyPod register codec.

The vectors are transcribed from the vendor application's C# expressions, not generated by a
simulator or by production codec code. They are not packet-capture golden vectors. Missing
production modules fail as ordinary tests so the suite still collects during the red TDD phase.
"""

from __future__ import annotations

import importlib
import inspect
from typing import Any

import pytest


class _MissingContract:
    def __init__(self, message: str) -> None:
        self.message = message

    def __getattr__(self, name: str) -> Any:
        pytest.fail(self.message, pytrace=False)


@pytest.fixture(scope="module")
def codec() -> Any:
    try:
        return importlib.import_module("energypod.adapters.modbus.protocol_codec")
    except (ImportError, AttributeError) as error:
        return _MissingContract(f"Protocol codec contract is not implemented: {error}")


@pytest.mark.parametrize(
    ("raw", "decoded"),
    [
        (0x0000, 0),
        (0x0001, 1),
        (0x7FFF, 32767),
        (0x8000, -32768),
        (0xF448, -3000),
        (0xFFFF, -1),
    ],
)
def test_signed_register_decode_matches_csharp_short_cast(
    codec: Any, raw: int, decoded: int
) -> None:
    """T-UNIT-PROTO-001 / V-WRITE / S0: ushort bits decode as signed int16."""
    assert codec.decode_signed16(raw) == decoded


@pytest.mark.parametrize(
    ("value", "raw"),
    [
        (-32768, 0x8000),
        (-3000, 0xF448),
        (-1, 0xFFFF),
        (0, 0x0000),
        (1, 0x0001),
        (32767, 0x7FFF),
    ],
)
def test_signed_register_encode_matches_csharp_ushort_cast(
    codec: Any, value: int, raw: int
) -> None:
    """T-UNIT-PROTO-002 / V-WRITE / S0: signed values retain two's-complement bits."""
    assert codec.encode_signed16(value) == raw


@pytest.mark.parametrize("value", [-32769, 32768, True, False, 1.5, "1", None])
def test_signed_register_encoder_rejects_instead_of_wrapping(codec: Any, value: Any) -> None:
    """T-UNIT-PROTO-003 / INV-RANGE-001 / S0: malformed commands never wrap."""
    with pytest.raises(codec.ProtocolValueError):
        codec.encode_signed16(value)


@pytest.mark.parametrize("raw", [-1, 65536, True, False, 1.5, "65535", None])
def test_signed_register_decoder_rejects_non_register_values(codec: Any, raw: Any) -> None:
    """T-UNIT-PROTO-004 / INV-RANGE-002 / S1."""
    with pytest.raises(codec.ProtocolValueError):
        codec.decode_signed16(raw)


def test_signed_register_round_trip_covers_all_ushort_bit_patterns(codec: Any) -> None:
    """T-UNIT-PROTO-005 / INV-RANGE-001 / S0: int16 conversion is exhaustive."""
    for raw in range(0x1_0000):
        assert codec.encode_signed16(codec.decode_signed16(raw)) == raw


@pytest.mark.parametrize(
    ("field_name", "words", "expected"),
    [
        # GetUintFromUshort(high, low) == (high << 16) | low.
        ("SYSTEM_HISTORY", (0x1234, 0x5678), 0x12345678),
        ("LEGACY_PCS_ENERGY", (0x1234, 0x5678), 0x12345678 * 0.1),
        ("LEGACY_BMS_ENERGY", (0x1234, 0x5678), 0x12345678 * 0.1),
        ("LEGACY_BECU_ENERGY", (0x1234, 0x5678), 0x12345678 * 0.001),
        ("LEGACY_BECU_CAPACITY", (0x1234, 0x5678), 0x12345678),
        # For the same lower-address-first input pair, these call sites reverse the helper args.
        ("IOT_BMS_ENERGY", (0x1234, 0x5678), 0x56781234 * 0.1),
        ("IOT_TOTAL_ENERGY", (0x1234, 0x5678), 0x56781234 * 0.1),
        ("RTU_ID", (0x1234, 0x5678), 0x56781234),
    ],
)
def test_field_specific_u32_reference_vectors(
    codec: Any,
    field_name: str,
    words: tuple[int, int],
    expected: int | float,
) -> None:
    """T-UNIT-PROTO-006 / V-SYS,V-IOT,V-LEGACY,V-LAYOUT / S0."""
    field = getattr(codec.UInt32Field, field_name)
    assert codec.decode_uint32(field, words) == pytest.approx(expected)


def test_u32_field_metadata_forbids_a_universal_word_order(codec: Any) -> None:
    """T-UNIT-PROTO-007 / INV-ENDIAN-001 / S0: every field family is explicit."""
    high_first = {
        "SYSTEM_HISTORY",
        "LEGACY_PCS_ENERGY",
        "LEGACY_BMS_ENERGY",
        "LEGACY_BECU_ENERGY",
        "LEGACY_BECU_CAPACITY",
    }
    low_first = {"IOT_BMS_ENERGY", "IOT_TOTAL_ENERGY", "RTU_ID"}

    for name in high_first:
        spec = codec.UINT32_CODECS[getattr(codec.UInt32Field, name)]
        assert spec.word_order is codec.WordOrder.HIGH_WORD_FIRST
    for name in low_first:
        spec = codec.UINT32_CODECS[getattr(codec.UInt32Field, name)]
        assert spec.word_order is codec.WordOrder.LOW_WORD_FIRST

    system_history = codec.UINT32_CODECS[codec.UInt32Field.SYSTEM_HISTORY]
    assert float(system_history.scale) == 1.0
    assert system_history.engineering_unit is None


@pytest.mark.parametrize(
    "words",
    [(), (1,), (1, 2, 3), (-1, 0), (0, 65536), (True, 0), (1.5, 0)],
)
def test_u32_decoder_requires_exactly_two_valid_registers(codec: Any, words: Any) -> None:
    """T-UNIT-PROTO-008 / INV-DECODE-001 / S1."""
    with pytest.raises(codec.ProtocolValueError):
        codec.decode_uint32(codec.UInt32Field.RTU_ID, words)


@pytest.mark.parametrize(
    ("active_w", "reactive_var", "registers"),
    [
        (0, 0, (0x0001, 0x0000, 0x0000)),
        (-3000, 750, (0x0001, 0xF448, 0x02EE)),
        (32767, -32768, (0x0001, 0x7FFF, 0x8000)),
    ],
)
def test_full_pq_payload_matches_vendor_three_register_expression(
    codec: Any,
    active_w: int,
    reactive_var: int,
    registers: tuple[int, int, int],
) -> None:
    """T-UNIT-PROTO-009 / V-WRITE / S0: FC16 payload is [1, P, Q]."""
    assert codec.encode_pq_registers(active_w, reactive_var) == registers


@pytest.mark.parametrize(
    ("active_w", "reactive_var"),
    [(-32769, 0), (32768, 0), (0, -32769), (0, 32768), (True, 0), (0, 1.0)],
)
def test_pq_payload_rejects_invalid_values_without_masking(
    codec: Any, active_w: Any, reactive_var: Any
) -> None:
    """T-UNIT-PROTO-010 / INV-RANGE-003 / S0."""
    with pytest.raises(codec.ProtocolValueError):
        codec.encode_pq_registers(active_w, reactive_var)


def test_zero_command_is_the_vendor_stop_payload(codec: Any) -> None:
    """T-UNIT-PROTO-011 / V-PQ-UI / S0."""
    assert codec.encode_stop_registers() == (1, 0, 0)


def test_wire_codec_does_not_claim_charge_or_discharge_direction(codec: Any) -> None:
    """T-UNIT-PROTO-012 / UNC-POWER-SIGN / S0: signed P is not a verified direction."""
    parameter_names = tuple(inspect.signature(codec.encode_pq_registers).parameters)

    assert parameter_names == ("active_w", "reactive_var")
    assert "charge" not in parameter_names
    assert "discharge" not in parameter_names
